version: 2.1

orbs:
  architect: giantswarm/architect@4.38.0

workflows:
  build:
    jobs:
    - architect/go-build:
        context: architect
        name: go-build
        binary: aws-tccpf-watchdog
        resource_class: xlarge
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        requires:
        - go-build
        filters:
            # Trigger the job also on git tag.
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-catalog:
        context: architect
        name: push-to-app-catalog
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: aws-tccpf-watchdog
        requires:
        - push-to-registries
        filters:
            # Trigger the job also on git tag.
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-collection:
        name: push-aws-tccpf-watchdog-to-aws-app-collection
        context: architect
        app_name: aws-tccpf-watchdog
        app_collection_repo: aws-app-collection
        requires:
        - push-to-app-catalog
        filters:
            # Only do this when a new tag is created.
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
