aws:
  accessKeyID: accesskey
  secretAccessKey: secretkey
  region: region

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
image:
  name: "giantswarm/aws-tccpf-watchdog"
  tag: "[[ .Version ]]"
registry:
  domain: docker.io

pod:
  user:
    id: 1000
  group:
    id: 1000

verticalPodAutoscaler:
  enabled: true

# Add seccomp to pod security context
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
securityContext:
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
